### ISSUE TITLE
Expo setup

### ISSUE THREAD

**Issue by YannCedric** [cometchat/cometchat-uikit-react-native#1]
Not sure if this fits into "bugs", (sorry if it doesn't)

I was wondering how to set it up with Expo? 

I followed all the steps from the readme and I'm getting the following error:

 
![Simulator Screen Shot - iPhone SE - 2021-02-12 at 22 27 06](https://user-images.githubusercontent.com/22302788/107840541-8e449480-6d81-11eb-89c0-815060ae817a.png)

> PS: Thank you so much for building this!

**Comment by ketanyekale** [comment]
It seems it was missed. Please try our latest v4 UI Kit.
