### ISSUE TITLE
When adding a member to a group the search doesn't work.

### ISSUE THREAD

**Issue by kiwioz** [cometchat/cometchat-uikit-react-native#30]
### Describe the problem

When adding a member to a group the search doesn’t work. It just says “Loading …”  when something is typed in the Search bar, but nothing ever loads. CometChat Logs the following Error

### What was the expected behavior?

Search loads members that match the search string

### Reproduction

It is reproducible every time.

1. Select Groups
2. Select a group from the list
3. Select the more options item from the header
4. Select "Add Members" 
5. Type in a simple search string in the Search Bar to search for the member you wish to add.
6. "Loading ..." will be displayed. If you press on the screen it will then show "Error". (see screen shots).

### Environment

React Native 0.63.4
cometchat-pro-react-native-ui-kit 3.0.0
cometchat-pro/react-native-chat 3.0.2

![Simulator Screen Shot - iPhone 11 - 2022-01-19 at 13 21 08](https://user-images.githubusercontent.com/70870133/150052289-c47e18d7-3fef-4330-9ac7-456ad2ae476a.png)
![Simulator Screen Shot - iPhone 11 - 2022-01-19 at 13 21 16](https://user-images.githubusercontent.com/70870133/150052303-1a3a91f2-df0e-4bae-b8bb-d965222c4151.png)

**Comment by SwethaSreeAvula** [comment]
This issue is fixed in the latest release
