### ISSUE TITLE
There is no documentation on how to use this UI Kit and customise my theme (change colors)

### ISSUE THREAD

**Issue by neeraj-nh** [cometchat/cometchat-uikit-react-native#31]

**Comment by paarthsabharwal** [comment]
Hi @neeraj-nh, Thank you for reaching out, and apologies for the delay in response. We do have our documentation and guide for our UI Kits available as a part of our documentation. You can refer to [this link](https://www.cometchat.com/docs/home/welcome) to find out more.
I hope this helps. Please let me know if you need any further help on this.
Regards, 
Paarth
Customer Success
